<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
	<PropertyGroup>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	</PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Implementations\Resources\Aspose.Total.lic" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Implementations\Resources\Aspose.Total.lic" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.Cells" Version="22.2.0" />
    <PackageReference Include="Aspose.HTML.Drawing" Version="25.5.0" />
    <PackageReference Include="Aspose.PDF" Version="22.2.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.25.0" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.6.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageReference Include="Microsoft.Graph" Version="3.10.0" />
    <PackageReference Include="Microsoft.Graph.Core" Version="1.21.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.17.1" />
    <PackageReference Include="morelinq" Version="3.3.2" />
    <PackageReference Include="Pds.Core.AzureStorage" Version="3.0.1" />
    <PackageReference Include="Pds.Core.CodeAnalysis.StyleCop" Version="2.0.0" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PDS.ViewYourFunding.DocumentGenerator.Repositories\PDS.ViewYourFunding.DocumentGenerator.Repositories.csproj" />
  </ItemGroup>

</Project>
